#include "ops/linear_attention/falcon_mamba_ssd/falcon_mamba_ssd.h"
#include <algorithm>
#include <cmath>
#include <cstdint>
#include <stdexcept>
namespace ninfer::ops::detail::falcon_mamba_ssd { namespace {
inline void check(cudaError_t e){if(e!=cudaSuccess)throw std::runtime_error(cudaGetErrorString(e));}
constexpr int H=kHeads,DH=kHeadDim,DS=kStateDim,BT=kChunkSize;
__device__ __forceinline__ std::int64_t si(int h,int d,int n){return (static_cast<std::int64_t>(h)*DH+d)*DS+n;}
__device__ __forceinline__ std::int64_t bi(int t,int h,int n){return (static_cast<std::int64_t>(t)*H+h)*DS+n;}
__device__ __forceinline__ std::int64_t xi(int t,int h,int d){return (static_cast<std::int64_t>(t)*H+h)*DH+d;}
__global__ void decay_prefix(const float*dt,const float*a,float*prefix,int tokens){int h=blockIdx.y;int t=blockIdx.x*blockDim.x+threadIdx.x;if(h>=H||t>=tokens)return;int base=(t/BT)*BT;float run=0;for(int j=base;j<=t;j++)run=fmaf(dt[j*H+h],a[h],run);prefix[t*H+h]=run;}
__global__ void chunk_state(const float*x,const float*b,const float*dt,const float*prefix,float*contrib,int tokens,int chunks){int idx=blockIdx.x*blockDim.x+threadIdx.x;constexpr int total=H*DH*DS;if(idx>=total*chunks)return;int chunk=idx/total;int local=idx%total;int n=local%DS,hd=local/DS,h=hd/DH,dim=hd%DH;int base=chunk*BT,end=min(base+BT,tokens);float sum=0.0f;for(int t=base;t<end;t++){float decay=expf(prefix[(end-1)*H+h]-prefix[t*H+h]);float source0=dt[t*H+h]*b[bi(t,h,n)];float source=source0*x[xi(t,h,dim)];sum+=decay*source;}contrib[idx]=sum;}
__global__ void state_passing(const float*prefix,const float*contrib,const float*s0,float*enter,float*final,int tokens,int chunks){int idx=blockIdx.x*blockDim.x+threadIdx.x;constexpr int total=H*DH*DS;if(idx>=total)return;int n=idx%DS,hd=idx/DS,h=hd/DH;float state=s0[idx];for(int chunk=0;chunk<chunks;chunk++){enter[static_cast<std::int64_t>(chunk)*total+idx]=state;int end=min((chunk+1)*BT,tokens);float decay=expf(prefix[(end-1)*H+h]);state=decay*state+contrib[static_cast<std::int64_t>(chunk)*total+idx];}final[idx]=state;}
__global__ void raw_chunk(const float*x,const float*b,const float*c,const float*dt,const float*d,const float*prefix,const float*chunk_starts,float*raw,int tokens){int t=blockIdx.x;int hd=blockIdx.y*blockDim.x+threadIdx.x;if(t>=tokens||hd>=H*DH)return;int h=hd/DH,dim=hd%DH;const int chunk=t/BT,base=chunk*BT;float acc=0.0f;for(int s=base;s<=t;s++){float factor=expf(prefix[t*H+h]-prefix[s*H+h])*dt[s*H+h]*x[xi(s,h,dim)];float inner=0;for(int n=0;n<DS;n++)inner=fmaf(b[bi(s,h,n)],c[bi(t,h,n)],inner);acc+=factor*inner;}float incoming=0;for(int n=0;n<DS;n++){float sv=chunk_starts[static_cast<std::int64_t>(chunk)*H*DH*DS+si(h,dim,n)];float decay=expf(prefix[t*H+h]);float ci=c[bi(t,h,n)];incoming+=(sv*decay)*ci;}raw[xi(t,h,dim)]=acc+incoming+d[h]*x[xi(t,h,dim)];}
}
std::size_t workspace_bytes(int tokens){if(tokens<=0)throw std::invalid_argument("Falcon SSD: tokens must be positive");const std::size_t chunks=(static_cast<std::size_t>(tokens)+BT-1)/BT;return static_cast<std::size_t>(tokens)*H*sizeof(float)+2*chunks*static_cast<std::size_t>(H)*DH*DS*sizeof(float);}
void launch(const float*x,const float*b,const float*c,const float*dt,const float*a,const float*d,const float*s0,float*raw,float*sout,int tokens,void*work,std::size_t workbytes,cudaStream_t stream){if(!x||!b||!c||!dt||!a||!d||!s0||!raw||!sout||!work||tokens<=0)throw std::invalid_argument("Falcon SSD: null/invalid input");auto required=workspace_bytes(tokens);if(workbytes<required)throw std::invalid_argument("Falcon SSD: workspace too small");auto*prefix=static_cast<float*>(work);const int chunks=(tokens+BT-1)/BT;const std::size_t total=static_cast<std::size_t>(H)*DH*DS;auto*contrib=prefix+static_cast<std::size_t>(tokens)*H;auto*starts=contrib+static_cast<std::size_t>(chunks)*total;decay_prefix<<<dim3((tokens+127)/128,H),128,0,stream>>>(dt,a,prefix,tokens);check(cudaGetLastError());chunk_state<<<(static_cast<std::size_t>(chunks)*total+255)/256,256,0,stream>>>(x,b,dt,prefix,contrib,tokens,chunks);check(cudaGetLastError());state_passing<<<(total+255)/256,256,0,stream>>>(prefix,contrib,s0,starts,sout,tokens,chunks);check(cudaGetLastError());raw_chunk<<<dim3(tokens,(H*DH+127)/128),128,0,stream>>>(x,b,c,dt,d,prefix,starts,raw,tokens);check(cudaGetLastError());}
}
