#include "artifact/v3_reader.h"
#include <algorithm>
#include <cstring>
#include <fstream>
#include <limits>
#include <set>
#include <stdexcept>
namespace ninfer::artifact::v3 {
namespace {
constexpr std::uint64_t A=4096,P=256; constexpr char M[]="NINFER\0\3"; constexpr char PM[]="NINFERP\0";
void fail(const std::string&s){throw std::runtime_error("v3 artifact: "+s);}
std::uint64_t add(std::uint64_t a,std::uint64_t b,const char*l){if(b>UINT64_MAX-a)fail(std::string(l)+" overflow");return a+b;}
std::uint64_t mul(std::uint64_t a,std::uint64_t b,const char*l){if(a&&b>UINT64_MAX/a)fail(std::string(l)+" overflow");return a*b;}
std::uint64_t align(std::uint64_t x,std::uint64_t a){return add(x,a-1,"alignment")/a*a;}
std::uint64_t u64(const std::byte*p){std::uint64_t x=0;for(int i=0;i<8;i++)x|=std::uint64_t(std::to_integer<unsigned char>(p[i]))<<(8*i);return x;}
std::vector<std::byte> read(const std::filesystem::path&p){std::ifstream f(p,std::ios::binary);if(!f)fail("open "+p.string());f.seekg(0,std::ios::end);auto n=f.tellg();if(n<0)fail("stat");f.seekg(0);std::vector<std::byte>b(static_cast<size_t>(n));f.read(reinterpret_cast<char*>(b.data()),n);if(!f)fail("truncated "+p.string());return b;}
void id(const std::byte*p,std::array<std::byte,16>&out){std::memcpy(out.data(),p,16);}
}
GptqG128Geometry gptq_g128_geometry(std::uint64_t k,std::uint64_t n){if(!k||!n||k%128||n%8)fail("GPTQ shape");auto groups=k/128,q=mul(mul(k/8,n,"qweight"),4,"qweight"),z=mul(mul(groups,n/8,"qzeros"),4,"qzeros"),s=mul(mul(groups,n,"scales"),2,"scales"),zo=align(q,P),so=align(add(zo,z,"qzeros"),P);return{k,n,groups,q,z,s,zo,so,add(so,s,"GPTQ")};}
Reader::Reader(const std::filesystem::path& entry){auto b=read(entry);if(b.size()<32||std::memcmp(b.data(),M,8)!=0)fail("invalid entry magic");auto n=u64(b.data()+8);id(b.data()+16,artifact_id_);auto end=add(32,n,"JSON");if(end>b.size())fail("JSON range");try{directory_=nlohmann::json::parse(reinterpret_cast<const char*>(b.data()+32),reinterpret_cast<const char*>(b.data()+end));}catch(...){fail("invalid JSON");}payload_offset_=align(end,A);if(payload_offset_>b.size())fail("payload offset");if(!directory_.is_object()||!directory_.contains("components")||!directory_.contains("objects")||!directory_.contains("bindings")||!directory_.contains("uses")||!directory_.contains("files"))fail("missing root member");if(!directory_["components"].is_object()||!directory_["components"].contains("text")||!directory_["components"]["text"].contains("config"))fail("missing text config");auto& fs=directory_["files"];if(!fs.is_array()||fs.empty())fail("invalid files");std::uint64_t logical=0;for(size_t i=0;i<fs.size();++i){auto& x=fs[i];if(!x.is_object()||!x.contains("path")||!x.contains("payload_bytes")||!x["payload_bytes"].is_number_unsigned()||!x["payload_bytes"].get<std::uint64_t>())fail("invalid file entry");if(i==0&&!x["path"].is_null())fail("files[0].path must be null");if(i>0&&!x["path"].is_string())fail("part path");if(x.contains("part_index")&&(!x["part_index"].is_number_unsigned()||x["part_index"].get<size_t>()!=i))fail("part index");auto bytes=x["payload_bytes"].get<std::uint64_t>();std::filesystem::path p=i?entry.parent_path()/x["path"].get<std::string>():entry;auto pb=read(p);if(i==0){if(pb.size()<payload_offset_+bytes)fail("entry payload");}else{if(pb.size()<32||std::memcmp(pb.data(),PM,8)!=0)fail("part magic");if(std::memcmp(pb.data()+8,artifact_id_.data(),16)!=0)fail("part artifact id");if(u64(pb.data()+24)!=i)fail("part header index");if(pb.size()<32+bytes)fail("part truncated");}parts_.push_back({p,logical,bytes});logical=add(logical,bytes,"logical payload");}logical_payload_bytes_=logical;
 std::set<std::string> names; for(auto&o:directory_["objects"]){if(!o.is_object()||!o.contains("name")||!o["name"].is_string()||o["name"].get<std::string>().empty()||!names.insert(o["name"]).second||!o.contains("kind")||!o.contains("offset")||!o.contains("bytes")||!o["offset"].is_number_unsigned()||!o["bytes"].is_number_unsigned()||!o["bytes"].get<std::uint64_t>())fail("malformed object");auto off=o["offset"].get<std::uint64_t>(),bytes=o["bytes"].get<std::uint64_t>();if(add(off,bytes,"object")>logical_payload_bytes_)fail("object bounds");if(o["kind"]=="tensor"){if(!o.contains("shape")||!o.contains("format")||!o.contains("layout"))fail("malformed tensor");auto fmt=o["format"].get<std::string>(),lay=o["layout"].get<std::string>();if(fmt=="gptq_q4_g128_fp16"&&lay=="gptq_canonical_k128_v1"){auto sh=o.at("shape");if(!sh.is_array()||sh.size()!=2||gptq_g128_geometry(sh.at(1),sh.at(0)).bytes!=bytes)fail("GPTQ encoded size");}else if(!((fmt=="bf16"||fmt=="BF16"||fmt=="fp32"||fmt=="FP32"||fmt=="int32"||fmt=="I32")&&(lay=="contiguous_le_v1"||lay=="contiguous-le-v1")))fail("unknown or incompatible tensor representation");}else if(o["kind"]!="resource")fail("invalid object kind");}
 std::set<std::string> bindings; for(auto&b:directory_["bindings"]){if(!b.is_object()||!b.contains("name")||!b.contains("object")||!b["object"].is_string()||!names.count(b["object"]))fail("invalid binding");if(!bindings.insert(b["name"].get<std::string>()).second)fail("duplicate binding");if(b.contains("parts")){if(!b["parts"].is_array()||b["parts"].empty())fail("invalid binding parts");for(auto&p:b["parts"]){if(!p.is_object()||!p.contains("object")||!names.count(p["object"].get<std::string>())||!p.contains("offset")||!p.contains("bytes")||!p["offset"].is_number_unsigned()||!p["bytes"].is_number_unsigned()||!p["bytes"].get<std::uint64_t>())fail("invalid binding part");auto po=p["offset"].get<std::uint64_t>(),pb=p["bytes"].get<std::uint64_t>();for(auto&oo:directory_["objects"])if(oo["name"]==p["object"]&&add(po,pb,"binding part")>oo["bytes"].get<std::uint64_t>())fail("binding part range");}}}
 std::set<std::pair<std::string,std::string>> uses; for(auto&u:directory_["uses"]){if(!u.is_object()||!u.contains("binding")||!bindings.count(u["binding"].get<std::string>()))fail("invalid use binding");auto key=std::make_pair(u.value("parameter",std::string{}),u.value("input",std::string{}));if(!uses.insert(key).second)fail("duplicate use");if(u.contains("auxiliaries")){if(!u["auxiliaries"].is_array())fail("invalid auxiliaries");for(auto&a:u["auxiliaries"])if(!bindings.count(a.get<std::string>()))fail("invalid auxiliary");}}
}
std::vector<std::byte> Reader::range(std::uint64_t off,std::uint64_t bytes)const{if(add(off,bytes,"range")>logical_payload_bytes_)fail("range bounds");std::vector<std::byte>out;out.reserve(bytes);while(bytes){auto it=std::find_if(parts_.begin(),parts_.end(),[&](const Part&p){return off>=p.logical_offset&&off<p.logical_offset+p.payload_bytes;});if(it==parts_.end())fail("range mapping");auto n=std::min(bytes,it->logical_offset+it->payload_bytes-off);auto b=read(it->path);auto base=it->path==parts_.front().path?payload_offset_:32;out.insert(out.end(),b.begin()+base+(off-it->logical_offset),b.begin()+base+(off-it->logical_offset)+n);off+=n;bytes-=n;}return out;}
std::vector<std::byte> Reader::payload(const std::string&name)const{for(auto&o:directory_["objects"])if(o.at("name")==name)return range(o.at("offset"),o.at("bytes"));fail("unknown object");return{};}
}
