#include "core/arena.h"
#include "core/device.h"
#include "core/layout.h"
#include "core/paged_kv_cache.h"
#include "core/candidate_continuation.h"
#include "targets/falcon_h1/falcon_h1_program.h"
#include "targets/falcon_h1/falcon_h1_attention.h"
#include "targets/qwen3_6/impl/runtime/logical_kv_store.h"
#include "targets/qwen3_6/impl/runtime/state_image_store.h"
#include <ninfer/targets/qwen3_6/state_image.h>
#include <iostream>
#include <stdexcept>
namespace { void check(bool b,const char*m){if(!b)throw std::runtime_error(m);} }
int main(){try{using namespace ninfer;namespace q=ninfer::targets::qwen3_6;namespace f=ninfer::targets::falcon_h1;namespace d=ninfer::targets::qwen3_6::detail;
 nlohmann::json config={{"hidden_size",3072},{"intermediate_size",12288},{"vocab_size",130049},{"num_hidden_layers",44},{"num_attention_heads",12},{"num_key_value_heads",2},{"head_dim",128},{"mamba_d_conv",4},{"mamba_n_heads",24},{"mamba_d_state",256},{"mamba_chunk_size",256},{"mamba_n_groups",1},{"mamba_d_head",128},{"mamba_d_ssm",3072},{"max_position_embeddings",8192},{"model_type","falcon_h1"},{"gptq_format","gptq_q4_g128_fp16"},{"gptq_layout","gptq_canonical_k128_v1"},{"input_perm","explicit_i32_auxiliary"},{"torch_dtype","bfloat16"},{"mamba_expand",2},{"mamba_norm_before_gate",false},{"mamba_rms_norm",true},{"mamba_proj_bias",false},{"mamba_conv_bias",true},{"rms_norm_eps",1e-5},{"rope_theta",1e11},{"attention_bias",false},{"mlp_bias",false},{"projectors_bias",false},{"tie_word_embeddings",false},{"mamba_use_mlp",true},{"embedding_multiplier",5.656854249492381},{"attention_in_multiplier",1.0},{"attention_out_multiplier",0.10416666666666667},{"key_multiplier",0.030690398488999456},{"ssm_in_multiplier",0.4166666666666667},{"ssm_out_multiplier",0.11785113019775793},{"lm_head_multiplier",0.013020833333333334},{"ssm_multipliers",{0.3535533905932738,0.25,0.1767766952966369,0.5,0.3535533905932738}},{"mlp_multipliers",{0.2946278254943948,0.032552083333333336}},{"quantization_config",{{"bits",4},{"group_size",128},{"desc_act",true},{"sym",true},{"quant_method","gptq"},{"checkpoint_format","gptq"},{"pack_dtype","int32"}}}};
 auto bound=f::bind_config_only(config);auto g=f::geometry_from_artifact(bound,8192);LayoutBuilder b;DeviceKVPagePoolSpec ps{.page_group_count=32,.geometry={.page_tokens=64,.device_plane_order=PagedKVPlaneOrder::PageMajor,.planes={{.dtype=DType::BF16,.leading_extent=128,.head_extent=2},{.dtype=DType::FP16,.leading_extent=128,.head_extent=2}}}};auto pl=plan_device_kv_page_pool(b,ps);auto tl=plan_kv_execution_tables(b,{.logical_page_capacity=16,.table_rows=6});q::StateImageSpec ss{.linear={.layers=44,.conv_channels=6656,.conv_width=4,.value_heads=24,.value_head_dim=128,.key_head_dim=256,.slot_count=6,.conv_dtype=DType::BF16},.hidden=3072};auto sl=q::plan_state_image_device_pool(b,ss);DeviceArena arena(b.finish(256));DeviceSpan backing{arena.base(),arena.capacity()};DeviceKVPagePool physical(backing,pl);KVExecutionTablePool tables(backing,tl,physical);d::LogicalKVPageStore pages(physical,64);d::KVAddressSpaceStore addresses(pages,tables,8,16);q::StateImageDevicePool state_physical(backing,sl);d::StateImageStore states(state_physical,nullptr,8);DeviceContext device(0);auto program=f::Package::make_program(bound,8192,16,4,2,addresses,states,state_physical);auto id=program.create_sequence(0);auto base=program.sequence(id).snapshot();auto candidate=program.sequence(id).begin({.kv_frontier=7,.position=7,.recurrent_version=base.recurrent_version+1});candidate.execute([&](ContinuationCandidateViews views){auto& store=candidate.kv_store_for_execution();store.ensure_mapped_to_tokens(views.kv,7,device.stream);auto cache=store.execution_layer_view(views.kv,0,128,2,KvCacheStorage::BFloat16);check(cache.block_table.data!=nullptr,"candidate table bound");store.commit_frontier(views.kv,7);});candidate.commit();auto committed=program.sequence(id).snapshot();check(committed.kv_frontier==7&&committed.position==7&&committed.generation==base.generation+1,"candidate descriptor committed");
 auto failed=program.sequence(id).begin({.kv_frontier=8,.position=8,.recurrent_version=committed.recurrent_version+1});bool threw=false;try{failed.execute([&](ContinuationCandidateViews views){auto& store=failed.kv_store_for_execution();store.ensure_mapped_to_tokens(views.kv,8,device.stream);throw std::runtime_error("injected attention failure");});}catch(const std::runtime_error&){threw=true;}check(threw,"candidate failure observed");check(program.sequence(id).snapshot()==committed,"rollback retained committed descriptor");check(addresses.committed_frontier(program.sequence(id).active_kv_handle())==7,"rollback retained committed KV frontier");program.release_sequence(id);check(physical.allocated_pages()==0&&physical.reserved_pages()==0&&states.occupied()==0,"smoke fixture resources released");std::cout<<"Falcon candidate attention seam host smoke passed\n";return 0;}catch(const std::exception&e){std::cerr<<"Falcon candidate attention seam host smoke failed: "<<e.what()<<'\n';return 1;}}
