#include "falcon_h1_attention.h"
#include "falcon_h1_program.h"
#include "d128_decode_donor.cuh"
#include "d128_prefill_donor_extracted.cuh"
#include "artifact/typed_binding.h"
#include "core/device.h"
#include "ops/kernel/paged_kv_address.cuh"
#include "ops/softmax_attention/dense/causal_cache/prompt_common.cuh"
#include <mma.h>
#include "ninfer/ops/linear.h"
#include "ninfer/ops/rope.h"
#include "targets/qwen3_6/impl/runtime/logical_kv_store.h"
#include <cuda_bf16.h>
#include <cmath>
#include <limits>
#include <stdexcept>
namespace ninfer::targets::falcon_h1 {
namespace {
constexpr int H=3072,QH=12,KVH=2,D=128;
__global__ void bf16_linear_generic(const __nv_bfloat16*x,const __nv_bfloat16*w,__nv_bfloat16*y,int K,int N,int T){int i=blockIdx.x*blockDim.x+threadIdx.x,total=N*T;if(i>=total)return;int n=i%N,t=i/N;float a=0.f;for(int k=0;k<K;++k)a=fmaf(__bfloat162float(w[(int64_t)n*K+k]),__bfloat162float(x[(int64_t)t*K+k]),a);y[i]=__float2bfloat16_rn(a);}
void linear_falcon(const Tensor&x,const Weight&w,Tensor&y,cudaStream_t s){if(w.qtype==QType::BF16_CTRL&&(w.n==1536||w.n==256||w.n==3072)){bf16_linear_generic<<<(w.n*y.ne[1]+255)/256,256,0,s>>>((const __nv_bfloat16*)x.data,(const __nv_bfloat16*)w.payload,(__nv_bfloat16*)y.data,w.k,w.n,y.ne[1]);CUDA_CHECK(cudaGetLastError());return;}ops::linear(x,w,y,s);}
__global__ void scale_copy(const __nv_bfloat16*x,__nv_bfloat16*y,std::size_t n,float a){std::size_t i=(std::size_t)blockIdx.x*blockDim.x+threadIdx.x;if(i<n)y[i]=__float2bfloat16_rn(__bfloat162float(x[i])*a);}
__global__ void positions_kernel(int*p,int base,int n){int i=blockIdx.x*blockDim.x+threadIdx.x;if(i<n)p[i]=base+i;}
void scale(const Tensor&x,Tensor&y,float a,cudaStream_t s){scale_copy<<<(x.numel()+255)/256,256,0,s>>>((const __nv_bfloat16*)x.data,(__nv_bfloat16*)y.data,x.numel(),a);CUDA_CHECK(cudaGetLastError());}
void tap(void*p,const Tensor&x,cudaStream_t s){if(p)CUDA_CHECK(cudaMemcpyAsync(p,x.data,x.bytes(),cudaMemcpyDeviceToDevice,s));}
__global__ void linear_to_head_major(const __nv_bfloat16*src,__nv_bfloat16*dst,int heads,int tokens){int i=blockIdx.x*blockDim.x+threadIdx.x,total=heads*D*tokens;if(i<total){int d=i%D,h=(i/D)%heads,t=i/(D*heads);dst[i]=src[(int64_t)t*heads*D+h*D+d];}}
__global__ void head_major_to_cache(const __nv_bfloat16*src,__nv_bfloat16*dst,int tokens){int i=blockIdx.x*blockDim.x+threadIdx.x,total=tokens*KVH*D;if(i<total){int d=i%D,h=(i/D)%KVH,t=i/(KVH*D);dst[i]=src[(int64_t)d+ D*((int64_t)h+KVH*t)];}}
__global__ void convert_q_fp16(const __nv_bfloat16*src,__half*dst,int n){int i=blockIdx.x*blockDim.x+threadIdx.x;if(i<n)dst[i]=__float2half_rn(__bfloat162float(src[i]));}
__global__ void append_d128(const __nv_bfloat16*k,const __nv_bfloat16*v,const int*positions,const int*table,__nv_bfloat16*kp,__half*vp,int tokens){int t=blockIdx.x,h=blockIdx.y,d=threadIdx.x;if(t>=tokens||d>=D)return;int pos=positions[t],pg=table[pos>>6];int64_t off=128LL*64*(h+KVH*pg)+128LL*(pos&63)+d;kp[off]=k[(int64_t)t*KVH*D+h*D+d];vp[off]=__float2half_rn(__bfloat162float(v[(int64_t)t*KVH*D+h*D+d]));}
__global__ void gather_cache_kv_d128(const __nv_bfloat16* kp,const __half* vp,const int* table,__nv_bfloat16* kout,__half* vout,int start,int tokens){int t=blockIdx.x,h=blockIdx.y,d=threadIdx.x;if(t>=tokens||h>=KVH||d>=D)return;int pos=start+t,pg=table[pos>>6];int64_t src=128LL*64*(h+KVH*pg)+128LL*(pos&63)+d;int64_t dst=(int64_t)t*KVH*D+h*D+d;if(kout)kout[dst]=kp[src];if(vout)vout[dst]=vp[src];}

}
std::size_t attention_workspace_bytes(std::size_t t){if(!t||t>INT_MAX)throw std::invalid_argument("Attention T invalid");WorkspaceLayoutBuilder b;(void)b.alloc(DType::BF16,{H,(int)t});(void)b.alloc(DType::BF16,{D,QH,(int)t});(void)b.alloc(DType::BF16,{D,KVH,(int)t});(void)b.alloc(DType::BF16,{D,KVH,(int)t});(void)b.alloc(DType::I32,{(int)t});(void)b.alloc(DType::BF16,{D,QH,(int)t});(void)b.alloc(DType::BF16,{H,(int)t});int parts=std::max(1,(int)((t+donor_d128::PART-1)/donor_d128::PART));return b.peak_bytes(256)+((std::size_t)QH*parts*D*sizeof(__half)+255&~std::size_t(255))+((std::size_t)2*QH*parts*sizeof(float)+255&~std::size_t(255));}
static void execute_attention_impl(Program&program,ContinuationCandidate&candidate,const ContinuationCandidateViews* supplied,const ContinuationDescriptor&base,std::uint64_t position,std::uint32_t layer,const BoundModel&model,const artifact::MaterializedArtifact&mat,const Tensor&input,Tensor&output,DeviceSpan ws,std::size_t ws_bytes,cudaStream_t stream,FalconAttentionTaps taps){
 const auto&g=program.geometry();int T=input.ne[1];if(layer>=g.layer_count||input.dtype!=DType::BF16||input.ne[0]!=H||T<1||output.dtype!=DType::BF16||output.ne[0]!=H||output.ne[1]!=T||position!=base.position||base.kv_frontier!=base.position||position+T>g.context_limit||ws.data==nullptr||ws_bytes>ws.bytes||ws_bytes<attention_workspace_bytes(T)||(reinterpret_cast<std::uintptr_t>(ws.data)&255U))throw std::invalid_argument("Falcon Attention invocation contract invalid");
 DeviceArena a(ws);auto scope=a.scope();Tensor x=a.alloc(DType::BF16,{H,T}),q=a.alloc(DType::BF16,{QH*D,T}),k=a.alloc(DType::BF16,{KVH*D,T}),v=a.alloc(DType::BF16,{KVH*D,T}),pos=a.alloc(DType::I32,{T}),attn=a.alloc(DType::BF16,{QH*D,T});auto w=[&](const char*r,int n,int m){auto&b=model.tensors.at("text/layers."+std::to_string(layer)+".self_attn."+r+".weight");return artifact::materialized_weight(mat,b.handle,artifact::NumericFormat::BF16,n,m);};
 positions_kernel<<<(T+255)/256,256,0,stream>>>((int*)pos.data,(int)position,T);CUDA_CHECK(cudaGetLastError());scale(input,x,(float)g.attention_in_multiplier,stream);linear_falcon(x,w("q_proj",QH*D,H),q,stream);linear_falcon(x,w("k_proj",KVH*D,H),k,stream);linear_falcon(x,w("v_proj",KVH*D,H),v,stream);CUDA_CHECK(cudaStreamSynchronize(stream));tap(taps.q,q,stream);tap(taps.k_pre_scale,k,stream);tap(taps.v,v,stream);scale(k,k,(float)g.key_multiplier,stream);CUDA_CHECK(cudaStreamSynchronize(stream));tap(taps.k,k,stream);Tensor q_rope(q.data,DType::BF16,{D,QH,T}),k_rope(k.data,DType::BF16,{D,KVH,T});ops::rope(pos,D,(float)g.rope_theta,q_rope,stream);ops::rope(pos,D,(float)g.rope_theta,k_rope,stream);tap(taps.post_rope_q,q,stream);tap(taps.post_rope_k,k,stream);CUDA_CHECK(cudaStreamSynchronize(stream));
 auto execute_kv=[&](ContinuationCandidateViews views){const int past_length=static_cast<int>(base.kv_frontier);const int candidate_frontier=past_length+T;auto& kv_store=candidate.kv_store_for_execution();kv_store.ensure_mapped_to_tokens(views.kv,static_cast<std::uint32_t>(candidate_frontier),stream);auto cache=kv_store.execution_layer_view(views.kv,layer,D,KVH,KvCacheStorage::BFloat16,PagedKVPlaneOrder::PageMajor);Tensor append_positions=pos;if(position!=base.kv_frontier){append_positions=a.alloc(DType::I32,{T});positions_kernel<<<(T+255)/256,256,0,stream>>>((int*)append_positions.data,(int)base.kv_frontier,T);CUDA_CHECK(cudaGetLastError());}append_d128<<<dim3(T,KVH),D,0,stream>>>((const __nv_bfloat16*)k.data,(const __nv_bfloat16*)v.data,(const int*)append_positions.data,(const int*)cache.block_table.data,(__nv_bfloat16*)cache.k_pages.data,(__half*)cache.v_pages.data,T);CUDA_CHECK(cudaGetLastError());if(taps.candidate_k||taps.candidate_v){gather_cache_kv_d128<<<dim3(T,KVH),D,0,stream>>>((const __nv_bfloat16*)cache.k_pages.data,(const __half*)cache.v_pages.data,(const int*)cache.block_table.data,(__nv_bfloat16*)taps.candidate_k,(__half*)taps.candidate_v,(int)base.kv_frontier,T);CUDA_CHECK(cudaGetLastError());}
 const int visible_kv_length=past_length+T;if(T==1){const int decode_visible_length=past_length+1;int parts=std::max(1,(decode_visible_length+donor_d128::PART-1)/donor_d128::PART);Tensor partial=a.alloc(DType::FP16,{D,QH,parts}),stats=a.alloc(DType::FP32,{2,QH,parts});donor_d128::partition<<<dim3(QH,parts),donor_d128::THREADS,0,stream>>>((const __nv_bfloat16*)q.data,(const __nv_bfloat16*)cache.k_pages.data,(const __half*)cache.v_pages.data,( __half*)partial.data,(float*)stats.data,(float*)stats.data+QH*parts,(const int*)cache.block_table.data,decode_visible_length,program.kv_store().physical_page_capacity(),QH,KVH,1.f/std::sqrt((float)D));CUDA_CHECK(cudaGetLastError());donor_d128::reduce<<<QH,donor_d128::THREADS,2*parts*sizeof(float),stream>>>((const __half*)partial.data,(const float*)stats.data,(const float*)stats.data+QH*parts,(__nv_bfloat16*)attn.data,decode_visible_length,parts);CUDA_CHECK(cudaGetLastError());}else{Tensor qhalf=a.alloc(DType::FP16,{D,QH,T});convert_q_fp16<<<(T*QH*D+255)/256,256,0,stream>>>((const __nv_bfloat16*)q.data,(__half*)qhalf.data,T*QH*D);CUDA_CHECK(cudaGetLastError());CUDA_CHECK(cudaFuncSetAttribute(donor_prefill::prefill_d128,cudaFuncAttributeMaxDynamicSharedMemorySize,sizeof(donor_prefill::SmemLayout)));donor_prefill::prefill_d128<<<dim3((T+donor_prefill::BM-1)/donor_prefill::BM,QH),donor_prefill::THREADS,sizeof(donor_prefill::SmemLayout),stream>>>((const __nv_bfloat16*)q.data,(const __nv_bfloat16*)cache.k_pages.data,(const __half*)cache.v_pages.data,(__nv_bfloat16*)attn.data,(const int*)cache.block_table.data,T,past_length,1.f/std::sqrt((float)D));CUDA_CHECK(cudaGetLastError());}linear_falcon(attn,w("o_proj",H,QH*D),output,stream);if(taps.pre_o||taps.o_projection||taps.output)CUDA_CHECK(cudaStreamSynchronize(stream));tap(taps.pre_o,attn,stream);tap(taps.o_projection,output,stream);scale(output,output,(float)g.attention_out_multiplier,stream);tap(taps.output,output,stream);CUDA_CHECK(cudaStreamSynchronize(stream));kv_store.commit_frontier(views.kv,static_cast<std::uint32_t>(candidate_frontier));};
 if (supplied) execute_kv(*supplied); else candidate.execute(execute_kv);
}
void execute_attention(Program&program,ContinuationCandidate&candidate,const ContinuationDescriptor&base,std::uint64_t position,std::uint32_t layer,const BoundModel&model,const artifact::MaterializedArtifact&mat,const Tensor&input,Tensor&output,DeviceSpan ws,std::size_t ws_bytes,cudaStream_t stream,FalconAttentionTaps taps){ execute_attention_impl(program,candidate,nullptr,base,position,layer,model,mat,input,output,ws,ws_bytes,stream,taps); }
void execute_attention_candidate(Program&program,ContinuationCandidate&candidate,const ContinuationCandidateViews&views,const ContinuationDescriptor&base,std::uint64_t position,std::uint32_t layer,const BoundModel&model,const artifact::MaterializedArtifact&mat,const Tensor&input,Tensor&output,DeviceSpan ws,std::size_t ws_bytes,cudaStream_t stream,FalconAttentionTaps taps){ execute_attention_impl(program,candidate,&views,base,position,layer,model,mat,input,output,ws,ws_bytes,stream,taps); }
} // namespace ninfer::targets::falcon_h1
