#include "falcon_h1_layer.h"
#include "falcon_h1_mamba.h"
#include "core/device.h"
#include "ninfer/ops/rmsnorm.h"
#include "artifact/typed_binding.h"
#include <cuda_bf16.h>
#include <cmath>
#include <stdexcept>
#include <fstream>
#include <filesystem>
namespace ninfer::targets::falcon_h1 { namespace {
constexpr int H=3072,I=9216;
__global__ void add_float(const float*a,const float*b,float*y,int n,float sa,float sb){int i=blockIdx.x*blockDim.x+threadIdx.x;if(i<n)y[i]=sa*a[i]+sb*b[i];}
__global__ void bf16_to_f32(const __nv_bfloat16*x,float*y,int n){int i=blockIdx.x*blockDim.x+threadIdx.x;if(i<n)y[i]=__bfloat162float(x[i]);}
__global__ void bf16_scaled(const __nv_bfloat16*x,float*y,int n,float s){int i=blockIdx.x*blockDim.x+threadIdx.x;if(i<n)y[i]=__bfloat162float(__float2bfloat16_rn(__bfloat162float(x[i])*s));}
__global__ void round_bf16(float*x,int n){int i=blockIdx.x*blockDim.x+threadIdx.x;if(i<n)x[i]=__bfloat162float(__float2bfloat16_rn(x[i]));}
__global__ void scale_round_bf16(float*x,int n,float s){int i=blockIdx.x*blockDim.x+threadIdx.x;if(i<n)x[i]=__bfloat162float(__float2bfloat16_rn(x[i]*s));}
__global__ void f32_to_bf16_scale(float*x,int n,float s){int i=blockIdx.x*blockDim.x+threadIdx.x;if(i<n)x[i]=__bfloat162float(__float2bfloat16_rn(x[i]*s));}
__global__ void scale_all(float*x,int n,float s){int i=blockIdx.x*blockDim.x+threadIdx.x;if(i<n)x[i]*=s;}
__global__ void silu_gate_mul(const float*g,const float*u,float*y,int n){int i=blockIdx.x*blockDim.x+threadIdx.x;if(i<n)y[i]=__bfloat162float(__float2bfloat16_rn((g[i]/(1.f+expf(-g[i])))*u[i]));}
__global__ void silu_mul(const float*g,const float*u,float*y,int n){int i=blockIdx.x*blockDim.x+threadIdx.x;if(i<n){float v=g[i];y[i]=(v/(1.f+expf(-v)))*u[i];}}
__global__ void residual(const __nv_bfloat16*a,const float*b,__nv_bfloat16*y,int n){int i=blockIdx.x*blockDim.x+threadIdx.x;if(i<n)y[i]=__float2bfloat16_rn(__bfloat162float(a[i])+b[i]);}
__global__ void add_bf16_residual(const __nv_bfloat16*a,const __nv_bfloat16*b,__nv_bfloat16*y,int n){int i=blockIdx.x*blockDim.x+threadIdx.x;if(i<n)y[i]=__float2bfloat16_rn(__bfloat162float(a[i])+__bfloat162float(b[i]));}
Weight bf16w(const artifact::MaterializedArtifact&m,const BoundModel&b,const std::string&n,int rows,int cols){return artifact::materialized_weight(m,b.tensors.at(n).handle,artifact::NumericFormat::BF16,rows,cols);}
}
std::size_t layer_workspace_bytes(std::size_t T){if(!T)throw std::invalid_argument("tokens zero");const auto mb=T==1?mamba_decode_workspace_bytes():mamba_prefill_workspace_bytes(T);return (static_cast<std::size_t>(H)*T*7+static_cast<std::size_t>(I)*3*T)*sizeof(float)+attention_workspace_bytes(T)+mb+8192;}
std::size_t layer_reference_workspace_bytes(std::size_t T){return layer_workspace_bytes(T)+2*static_cast<std::size_t>(H)*T*sizeof(float);}
void execute_layer_reference(Program&p,std::uint64_t seq,std::uint32_t layer,const BoundModel&b,const artifact::MaterializedArtifact&m,GptqExecution&g,const Tensor&x,Tensor&y,DeviceSpan ws,std::size_t bytes,cudaStream_t s){execute_layer(p,seq,layer,b,m,g,x,y,ws,bytes,s,{});}
void capture_layer_reference_taps(Program&p,std::uint64_t seq,std::uint32_t layer,const BoundModel&b,const artifact::MaterializedArtifact&m,GptqExecution&g,const Tensor&x,Tensor&y,DeviceSpan ws,std::size_t bytes,cudaStream_t s,const std::string& dir){std::filesystem::create_directories(dir);const auto n=x.bytes();DeviceBuffer tapsbuf(n*3);FalconAttentionTaps at;at.pre_o=tapsbuf.p;at.output=static_cast<std::byte*>(tapsbuf.p)+n;at.candidate_k=static_cast<std::byte*>(tapsbuf.p)+2*n;execute_layer(p,seq,layer,b,m,g,x,y,ws,bytes,s,at);CUDA_CHECK(cudaStreamSynchronize(s));std::vector<std::byte> buf(n*3);CUDA_CHECK(cudaMemcpy(buf.data(),tapsbuf.p,buf.size(),cudaMemcpyDeviceToHost));for(int i=0;i<3;++i){std::ofstream f(dir+(i==0?"/attention_pre_o.bf16":i==1?"/attention_output.bf16":"candidate_k.bf16"),std::ios::binary);f.write((char*)buf.data()+i*n,n);if(!f)throw std::runtime_error("layer reference tap write failed");}CUDA_CHECK(cudaMemcpy(buf.data(),y.data,n,cudaMemcpyDeviceToHost));std::ofstream out(dir+"/layer_output.bf16",std::ios::binary);out.write((char*)buf.data(),n);if(!out)throw std::runtime_error("layer reference output write failed");}
void execute_layer(Program&p,std::uint64_t seq,std::uint32_t layer,const BoundModel&b,const artifact::MaterializedArtifact&m,GptqExecution&gptq,const Tensor&input,Tensor&output,DeviceSpan ws,std::size_t ws_bytes,cudaStream_t stream,FalconAttentionTaps taps){
 if(layer>=b.layer_count||input.dtype!=DType::BF16||input.ne[0]!=H||!input.is_contiguous()||output.dtype!=DType::BF16||output.ne[0]!=H||output.ne[1]!=input.ne[1]||output.data==input.data)throw std::invalid_argument("Falcon hybrid input/output mismatch");const int T=input.ne[1];if(!ws.data||ws_bytes>ws.bytes||ws_bytes<layer_workspace_bytes(T)||(reinterpret_cast<std::uintptr_t>(ws.data)&255U))throw std::invalid_argument("Falcon layer workspace too small");auto& owner=p.sequence(seq);const auto base=owner.snapshot();if(p.kv_frontier(seq)!=base.kv_frontier)throw std::logic_error("committed Falcon KV frontier diverges from descriptor before layer");auto candidate=owner.begin({base.kv_frontier+T,base.position+T,base.recurrent_version+1});try {candidate.execute([&](ContinuationCandidateViews views){DeviceArena a(ws);auto scope=a.scope();Tensor norm=a.alloc(DType::BF16,{H,T}),att=a.alloc(DType::BF16,{H,T}),merged=a.alloc(DType::BF16,{H,T}),ffn_norm=a.alloc(DType::BF16,{H,T}),residual1=a.alloc(DType::BF16,{H,T}),mlp_bf=a.alloc(DType::BF16,{H,T});float* mamba_out=(float*)a.alloc_bytes((std::size_t)H*T*4).data;float* ffn_input=(float*)a.alloc_bytes((std::size_t)H*T*4).data;float* gate=(float*)a.alloc_bytes((std::size_t)I*T*4).data;float*up=(float*)a.alloc_bytes((std::size_t)I*T*4).data;float*act=(float*)a.alloc_bytes((std::size_t)I*T*4).data;float*down=(float*)a.alloc_bytes((std::size_t)H*T*4).data;
 const std::string root="text/layers."+std::to_string(layer)+".";ops::rmsnorm(input,Tensor(m.device_data(b.tensors.at(root+"input_layernorm.weight").handle),DType::BF16,{H}),static_cast<float>(p.geometry().rms_norm_eps),false,norm,stream);if(taps.q)CUDA_CHECK(cudaMemcpyAsync(taps.q,norm.data,norm.bytes(),cudaMemcpyDeviceToDevice,stream));
 p.copy_candidate_state(views.recurrent,stream);const auto dest=p.mamba_candidate_state_view(views.recurrent,layer);float* mamba_input=(float*)a.alloc_bytes((std::size_t)H*T*sizeof(float)).data;bf16_scaled<<<(H*T+255)/256,256,0,stream>>>((const __nv_bfloat16*)norm.data,mamba_input,H*T,1.f);CUDA_CHECK(cudaGetLastError());
 if(T==1){MambaDecodeTaps mt;mt.out_proj=mamba_out;mamba_decode(b,m,layer,mamba_input,dest,mamba_decode_workspace_view((float*)a.alloc_bytes(mamba_decode_workspace_bytes()).data,mamba_decode_workspace_bytes()),mt,stream);}else {MambaPrefillTaps mt;mt.out_proj=mamba_out;mamba_prefill(b,m,layer,mamba_input,T,dest,mamba_prefill_workspace_view((float*)a.alloc_bytes(mamba_prefill_workspace_bytes(T)).data,mamba_prefill_workspace_bytes(T),T),mt,stream);}
 const std::size_t att_offset=(a.used()+255)&~std::size_t(255);DeviceSpan att_ws{static_cast<std::byte*>(ws.data)+att_offset,ws_bytes-att_offset};FalconAttentionTaps at=taps;execute_attention_candidate(p,candidate,views,base,base.position,layer,b,m,norm,att,att_ws,att_ws.bytes,stream,at);
 // Attention output already includes its configured multiplier. Apply the Mamba output
 // multiplier at the frozen FP32->BF16 branch boundary, then add both branches in FP32.
 f32_to_bf16_scale<<<(H*T+255)/256,256,0,stream>>>(mamba_out,H*T,static_cast<float>(p.geometry().ssm_out_multiplier));CUDA_CHECK(cudaGetLastError());
 float* att_f32=(float*)a.alloc_bytes((std::size_t)H*T*sizeof(float)).data;bf16_scaled<<<(H*T+255)/256,256,0,stream>>>((const __nv_bfloat16*)att.data,att_f32,H*T,1.f);CUDA_CHECK(cudaGetLastError());
 add_float<<<(H*T+255)/256,256,0,stream>>>(att_f32,mamba_out,mamba_out,H*T,1.f,1.f);CUDA_CHECK(cudaGetLastError());
 residual<<<(H*T+255)/256,256,0,stream>>>((const __nv_bfloat16*)input.data,mamba_out,(__nv_bfloat16*)residual1.data,H*T);CUDA_CHECK(cudaGetLastError());CUDA_CHECK(cudaMemcpyAsync(merged.data,residual1.data,residual1.bytes(),cudaMemcpyDeviceToDevice,stream));
 ops::rmsnorm(merged,Tensor(m.device_data(b.tensors.at(root+"pre_ff_layernorm.weight").handle),DType::BF16,{H}),static_cast<float>(p.geometry().rms_norm_eps),false,ffn_norm,stream);
 if(taps.output)CUDA_CHECK(cudaMemcpyAsync(taps.output,ffn_norm.data,ffn_norm.bytes(),cudaMemcpyDeviceToDevice,stream));const std::string ffn="text/layers/"+std::to_string(layer)+"/ffn/";if(!gptq.staged())throw std::logic_error("GPTQ permutations must be staged before hybrid layer execution");bf16_to_f32<<<(H*T+255)/256,256,0,stream>>>((const __nv_bfloat16*)ffn_norm.data,ffn_input,H*T);CUDA_CHECK(cudaGetLastError());gptq.linear(ffn+"gate_proj",ffn_input,gate,T,stream);gptq.linear(ffn+"up_proj",ffn_input,up,T,stream);round_bf16<<<(I*T+255)/256,256,0,stream>>>(gate,I*T);CUDA_CHECK(cudaGetLastError());round_bf16<<<(I*T+255)/256,256,0,stream>>>(up,I*T);CUDA_CHECK(cudaGetLastError());scale_all<<<(I*T+255)/256,256,0,stream>>>(gate,I*T,static_cast<float>(p.geometry().gate_multiplier));CUDA_CHECK(cudaGetLastError());silu_gate_mul<<<(I*T+255)/256,256,0,stream>>>(gate,up,act,I*T);CUDA_CHECK(cudaGetLastError());round_bf16<<<(I*T+255)/256,256,0,stream>>>(act,I*T);CUDA_CHECK(cudaGetLastError());gptq.linear(ffn+"down_proj",act,down,T,stream);round_bf16<<<(H*T+255)/256,256,0,stream>>>(down,H*T);CUDA_CHECK(cudaGetLastError());scale_round_bf16<<<(H*T+255)/256,256,0,stream>>>(down,H*T,static_cast<float>(p.geometry().down_multiplier));CUDA_CHECK(cudaGetLastError());add_bf16_residual<<<(H*T+255)/256,256,0,stream>>>((const __nv_bfloat16*)residual1.data,(const __nv_bfloat16*)down,(__nv_bfloat16*)output.data,H*T);CUDA_CHECK(cudaGetLastError());});candidate.prepare();candidate.commit(); } catch (...) { candidate.rollback(); throw; }
}
}
